### ISSUE TITLE
希望某位先辈呼吁所有人去特定的帖子留言

### ISSUE THREAD

**Issue by RealFakeAccount** [lixiang810/listofnobar#11]
然后定时用爬虫更新列表

**Comment by BeiyanYunyi** [comment]
收到，我尝试去吧务群问问。
话说Github Actions可以定时执行吗？这样方便些，不然我要在自己服务器上搞

**Comment by RealFakeAccount** [comment]
我记得GitHub action有个类似Crontab的东西
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

**Comment by BeiyanYunyi** [comment]
> 我记得GitHub action有个类似Crontab的东西
> https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule

好，以后有空搞，我正在和吧务商量集中楼了

**Comment by BeiyanYunyi** [comment]
另外我建repo时选了GPL协议，你的爬虫要GPL吗，还是我换协议？

**Comment by RealFakeAccount** [comment]
> 
> 
> 另外我建repo时选了GPL协议，你的爬虫要GPL吗，还是我换协议？

不要紧 ,按GPL来
反正总共才100行不到

**Comment by RealFakeAccount** [comment]
麻烦提醒一下让先辈们别发到楼中楼里面

**Comment by BeiyanYunyi** [comment]
> 麻烦提醒一下让先辈们别发到楼中楼里面

已经提醒了

**Comment by BeiyanYunyi** [comment]
雅塔贼，爬虫部署完毕了
